# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca1e5de624c534edfc16c1c6a58499ab0374a46a80ccc9eb05d3e0b79ae151c378ff2fbd233d50cb8537c46f341d77007de344e7da0bfafd077d469962520f2

test:
  secret_key_base: 3e11ab6933d983605ec1d4619fbed748bd2c4d91dd4c489a0dd1b8d263a275488a1a54f1d7b042ae10d7d0b25118ac5b2b0075540e43fa4a8bef2b02c02311ee

# Do not keep production secrets in the repository,
# instead read values from the environment.

# TODO: DANGER! handle from ansible main host to the container
production:
  secret_key_base: 33de8444faed418a7b3be6f6f9d5fd734abd4214d61d0dd1b08d4360e54cdd270b708f3f2ed0580216396a16402d6f49a48445a81e73b7857a302b94be0f2f3a
